name: FTP Deploy

on:
  push:
    branches:
      - main # oder master, je nachdem wie dein Haupt-Branch heißt

jobs:
  ftp-deploy:
    name: Upload to Mittwald via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
